# Generated by Django 2.1.5 on 2020-07-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='postion',
            new_name='position',
        ),
    ]
